meta_product_name: "Sampompom"
meta_title: "Sampompom - Discover Japan's Shoutengai"
meta_description: "Sampompom - Get closer, discover a local shopping street, interact and find new shops"
meta_image: "sampompom.sml.2shoesNwords" # should exist in `app/assets/images/`
